# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Build & Lint & Test

on:
  workflow_dispatch:

  pull_request:

  push:
    branches:
      - next

env:
  NODE_VERSION: lts/*

jobs:
  main:
    name: Build & Lint & Test
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: ⤵️ Checkout repository
        uses: actions/checkout@v4

      - name: 🏗 Setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: 🏗 Setup nodejs corepack
        run: corepack enable

      - name: 🏗 Get yarn config
        id: yarn_config
        run: echo "cache_folder=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

      - name: 🏗 Cache Layer
        uses: actions/cache@v4
        with:
          path: ${{ steps.yarn_config.outputs.cache_folder }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: 🏗 Install dependencies
        run: yarn install --immutable

      - name: 🏗 Cache Wireit
        uses: google/wireit@setup-github-actions-caching/v2

      - name: 🚀 Build Typescript
        run: WIREIT_LOGGER=metrics yarn build

      - name: 🚀 Run ESLint
        run: WIREIT_LOGGER=metrics yarn lint

      - name: 🚀 Run Test
        run: WIREIT_LOGGER=metrics yarn test
