# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Build & Lint & Test

on:
  workflow_dispatch:

  pull_request:

  push:
    branches:
      - next

jobs:
  main:
    uses: the-nexim/actions/.github/workflows/build-lint-test.yaml@v1

    permissions:
      contents: read

    with:
      node-version: lts/*
