# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Publish NPM

on:
  workflow_dispatch:

  release:
    types:
      - created

env:
  NODE_VERSION: lts/*

jobs:
  main:
    uses: the-nexim/actions/.github/workflows/publish-npm.yaml@v1
    permissions:
      contents: read
      id-token: write
    with:
      node-version: lts/*
    secrets: inherit
