# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Publish NPM

on:
  workflow_dispatch:

  release:
    types:
      - created

env:
  NODE_VERSION: lts/*

jobs:
  publish-npm:
    if: github.repository_owner == 'the-nexim'

    name: Publish NPM
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: ⤵️ Checkout repository
        uses: actions/checkout@v4

      - name: 🏗 Setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: 'https://registry.npmjs.org'

      - name: 🏗 Setup nodejs corepack
        run: corepack enable

      - name: 🏗 Get yarn config
        id: yarn_config
        run: echo "cache_folder=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

      - name: 🏗 Cache Layer
        uses: actions/cache@v4
        with:
          path: ${{ steps.yarn_config.outputs.cache_folder }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: 🏗 Install dependencies
        run: yarn install --immutable

      - name: 🏗 Build
        run: WIREIT_LOGGER=metrics yarn build
        env:
          NODE_ENV: production

      - name: 🚀 Publish
        run: WIREIT_LOGGER=metrics yarn run publish -- --yes
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
